inherit_from:
  - https://raw.githubusercontent.com/trinistr/rubocop-config/main/rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

ThreadSafety/ClassInstanceVariable:
  Exclude:
    # Class variables should only be modified during class loading.
    - lib/browser_of_babel/holotheca.rb
