inherit_from:
  - https://raw.githubusercontent.com/trinistr/rubocop-config/main/rubocop.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-yard

# Class variables should only be modified during class loading.
ThreadSafety/ClassInstanceVariable:
  Exclude:
    - lib/browser_of_babel/holotheca.rb
    - lib/browser_of_babel/holotheca/holarchy.rb
ThreadSafety/ClassAndModuleAttributes:
  Exclude:
    - lib/browser_of_babel/holotheca.rb
