#!/usr/bin/env ruby
# frozen_string_literal: true

require "browser_of_babel"

if ARGV.empty? || ARGV.include?("-h") || ARGV.include?("--help")
  puts <<~TEXT
    Usage:
      browser_of_babel "hex3.1.2.3.5[10-100,200-300]" "000.4.5.32.410[1]"
  TEXT
  return
end
if ARGV.include?("-v") || ARGV.include?("--version")
  puts BrowserOfBabel::VERSION
  return
end

ARGV.map do |arg|
  puts BrowserOfBabel::Locator.new.call(arg.strip)
rescue BrowserOfBabel::Error => e
  warn "#{e.class}: #{e.message}"
end
